### ISSUE TITLE
Environment variable GSDK_CONFIG_FILE not defined

### ISSUE THREAD

**Issue by ghost** [natepac/playfabmirrorgameexample#3]
I'm getting the following error when running the client:
  **Environment variable GSDK_CONFIG_FILE not defined**
  UnityEngine.Debug:LogError(Object)
  PlayFab.PlayFabMultiplayerAgentAPI:Start() (at Assets/PlayFabSdk/MultiplayerAgent/PlayFabMultiplayerAgentAPI.cs:71)
  ServerStartUp:StartRemoteServer() (at Assets/Scripts/ServerStartUp.cs:40)
  ServerStartUp:Start() (at Assets/Scripts/ServerStartUp.cs:24)

**Comment by ghost** [comment]
I was running the client using REMOTE_SERVER instead of REMOTE_CLIENT

**Comment by charan-vendra** [comment]
I still get this error on server.
